### ISSUE TITLE
Определение поля

### ISSUE THREAD

**Issue by denyszamiatin** [denyszamiatin/Monopoly#9]
Создать структуру данных для определения положения игрока на игровом поле. Данная структура должна возвращать новую позицию игрока (номер клетки) в зависимости от выброшенных костей.

**Comment by ZlatanMLG** [comment]
Done

**Comment by denyszamiatin** [comment]
В этой задаче должен быть реализован класс для представления игрового поля

**Comment by katafalk2009** [comment]
done
